apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: example-slack-notifier
spec:
  notification:
    filter: build.status in [Build.Status.SUCCESS, Build.Status.FAILURE, Build.Status.INTERNAL_ERROR, Build.Status.TIMEOUT]
    params:
      buildStatus: $(build.status)
      buildTriggerName: $(build.substitutions['TRIGGER_NAME'])
      buildRepository: $(build.substitutions['REPO_NAME'])
      buildBranch: $(build.substitutions['BRANCH_NAME'])
      buildCommit: $(build.substitutions['SHORT_SHA'])
    delivery:
      webhookUrl:
        secretRef: webhook-url
    template:
      type: golang
      uri: gs://dulcet-day-419100-notifiers-config/slack.json
  secrets:
    - name: webhook-url
      value: projects/387664188827/secrets/slack-webhook-url/versions/latest
