# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
# Build the binary and put it into the builder image.
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag=us-docker.pkg.dev/devops-309220/metrio/slack-build-notifier:$COMMIT_SHA
  - --file=./slack/Dockerfile
  - '.'
# Run the smoketest to verify that everything built correctly.
- name: us-docker.pkg.dev/devops-309220/metrio/slack-build-notifier:$COMMIT_SHA
  args:
  - --smoketest
  - --alsologtostderr

# Push the image with tags.
images:
- us-docker.pkg.dev/devops-309220/metrio/slack-build-notifier:$COMMIT_SHA

tags:
- cloud-build-notifiers-slack
