substitutions:
  # these variable are expected to remain static across environments
  _IMAGE_NAME: us-docker.pkg.dev/bf-artifact-registry/bf-docker-registry/bf-product/cloud-build-notifiers

steps:
  - id: Docker Build
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --dockerfile=slack/Dockerfile
      - --build-arg=BRANCH_NAME=${BRANCH_NAME}
      - --build-arg=BUILD_PROJECT=${PROJECT_ID}
      - --build-arg=BUILD_ID=${BUILD_ID}
      - --build-arg=BUILD_SERVICE=cloudbuild
      - --destination=${_IMAGE_NAME}:${SHORT_SHA}
      - --cache=true
